server:
  port: 8001
  
spring:
  application:
    name: department-service

# Spring Cloud bas
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    
# Zipkin
  zipkin:
    enabled: true
    base-url: http://localhost:9411/
    
  sleuth:
    enabled: true